import BakimMamasi from "../images/caudae/Amaranth-Purple.jpg";
import PerformansMamasi from "../images/caudae/Bangladesh-Green.jpg";
import YuksekEnerjiMamasi from "../images/caudae/Chocolate-Cosmos.jpg";
import YavruKopekMamasi from "../images/caudae/Cinereous.jpg";
import EkonomikMama from "../images/caudae/Dark-Lavender.jpg";
import EagerToMeat from "../images/fabled/Eager-To-Meat.png";
import GentleGiants from "../images/fabled/Gentle-Giants.png";
import GrowLittleOne from "../images/fabled/Grow-Little-One.png";
import HappyToSea from "../images/fabled/Happy-To-Sea.png";
import WellBegun from "../images/fabled/Well-Begun.png";
import Robbie from "../images/holistic/Robbies.png";

export const items = [
  {
    id: 1,
    category: "caudae",
    img: BakimMamasi,
    name: "Bakim Mamasi",
    price: 57,
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque hic repellat temporibus, voluptates dolorem tenetur libero impedit quos veniam sit. Numquam ab non omnis quas fugiat suscipit in, exercitationem dolores",
    texture: "Lamb and Rice",
    weight: "5kg",
    size: "Puppy",
  },
  {
    id: 2,
    category: "caudae",
    img: PerformansMamasi,
    name: "Performans Mamasi",
    price: 73,
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque hic repellat temporibus, voluptates dolorem tenetur libero impedit quos veniam sit. Numquam ab non omnis quas fugiat suscipit in, exercitationem dolores",
    texture: "Lamb and Rice",
    weight: "5kg",
    size: "Adult",
  },
  {
    id: 3,
    category: "caudae",
    img: YuksekEnerjiMamasi,
    name: "Yuksek Enerji Mamasi",
    price: 64,
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque hic repellat temporibus, voluptates dolorem tenetur libero impedit quos veniam sit. Numquam ab non omnis quas fugiat suscipit in, exercitationem dolores",
    texture: "salmon and Rice",
    weight: "5kg",
    size: "Adult",
  },
  {
    id: 4,
    category: "caudae",
    img: YavruKopekMamasi,
    name: "Yavru Kopek Mamasi",
    price: 85,
    des: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores nihil ducimus voluptas possimus nisi quas quo nobis maxime at placeat, Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae, ea!",
    texture: "Lamb and Rice",
    weight: "5kg",
    size: "Puppy",
  },
  {
    id: 5,
    category: "caudae",
    img: EkonomikMama,
    name: "Ekonomik Mama",
    price: 69,
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque hic repellat temporibus, voluptates dolorem tenetur libero impedit quos veniam sit. Numquam ab non omnis quas fugiat suscipit in, exercitationem dolores",
    texture: "Salmon and Rice",
    weight: "5kg",
    size: "Adult",
  },
  {
    id: 6,
    category: "fabled",
    img: EagerToMeat,
    name: "Eager To Meat",
    price: 54,
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque hic repellat temporibus, voluptates dolorem tenetur libero impedit quos veniam sit. Numquam ab non omnis quas fugiat suscipit in, exercitationem dolores",
    texture: "Chicken and Rice",
    weight: "2kg",
    size: "Adult",
  },
  {
    id: 7,
    category: "fabled",
    img: GentleGiants,
    name: "Gentle Giants",
    price: 85,
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque hic repellat temporibus, voluptates dolorem tenetur libero impedit quos veniam sit. Numquam ab non omnis quas fugiat suscipit in, exercitationem dolores.",
    texture: "Tuna and Rice",
    weight: "2kg",
    size: "Puppy",
  },
  {
    id: 8,
    category: "fabled",
    img: GrowLittleOne,
    name: "Grow Little One",
    price: 76,
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque hic repellat temporibus, voluptates dolorem tenetur libero impedit quos veniam sit. Numquam ab non omnis quas fugiat suscipit in, exercitationem dolores.",
    texture: "White Fish",
    weight: "2kg",
    size: "Puppy",
  },
  {
    id: 9,
    category: "fabled",
    img: HappyToSea,
    name: "Happy To Sea",
    price: 94,
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque hic repellat temporibus, voluptates dolorem tenetur libero impedit quos veniam sit. Numquam ab non omnis quas fugiat suscipit in, exercitationem dolores",
    texture: "Chicken and Rice",
    weight: "2kg",
    size: "Adult",
  },
  {
    id: 10,
    category: "fabled",
    img: WellBegun,
    name: "Well Begun",
    price: 87,
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque hic repellat temporibus, voluptates dolorem tenetur libero impedit quos veniam sit. Numquam ab non omnis quas fugiat suscipit in, exercitationem dolores",
    texture: "Chicken and Rice",
    weight: "2kg",
    size: "Puppy",
  },
  {
    id: 11,
    category: "holistic",
    img: Robbie,
    name: "Robbie Cuisine",
    price: 101,
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque hic repellat temporibus, voluptates dolorem tenetur libero impedit quos veniam sit. Numquam ab non omnis quas fugiat suscipit in, exercitationem dolores",
    texture: "Wheat and Vegetable",
    weight: "3kg",
    size: "Adult",
  },
];
